// Generated by scripts/generate-functions-data.ts — do not edit.
// Source: data/providers.json

export interface ProviderRedirect {
  name: string;
  url: string;
  template: string | null;
  env: string | null;
}

export const PROVIDERS: Record<string, ProviderRedirect> = {
  "runpod": {
    "name": "RunPod",
    "url": "https://www.runpod.io",
    "template": "https://runpod.io?ref={REF}",
    "env": "RUNPOD_REF"
  },
  "vast-ai": {
    "name": "Vast.ai",
    "url": "https://vast.ai",
    "template": "https://vast.ai/?ref_id={REF}",
    "env": "VAST_REF"
  },
  "lambda-labs": {
    "name": "Lambda Labs",
    "url": "https://lambdalabs.com",
    "template": "https://lambdalabs.com/service/gpu-cloud?ref={REF}",
    "env": "LAMBDA_REF"
  },
  "paperspace": {
    "name": "Paperspace",
    "url": "https://www.paperspace.com",
    "template": "https://www.paperspace.com/?r={REF}",
    "env": "PAPERSPACE_REF"
  },
  "modal": {
    "name": "Modal",
    "url": "https://modal.com",
    "template": "https://modal.com",
    "env": null
  },
  "coreweave": {
    "name": "CoreWeave",
    "url": "https://www.coreweave.com",
    "template": "https://www.coreweave.com",
    "env": null
  },
  "tensordock": {
    "name": "TensorDock",
    "url": "https://tensordock.com",
    "template": "https://tensordock.com/?ref={REF}",
    "env": "TENSORDOCK_REF"
  },
  "genesis-cloud": {
    "name": "Genesis Cloud",
    "url": "https://www.genesiscloud.com",
    "template": "https://www.genesiscloud.com",
    "env": null
  },
  "hyperstack": {
    "name": "Hyperstack",
    "url": "https://www.hyperstack.cloud",
    "template": "https://www.hyperstack.cloud/?ref={REF}",
    "env": "HYPERSTACK_REF"
  },
  "together-ai": {
    "name": "Together AI",
    "url": "https://www.together.ai",
    "template": "https://www.together.ai/?ref={REF}",
    "env": "TOGETHER_REF"
  },
  "replicate": {
    "name": "Replicate",
    "url": "https://replicate.com",
    "template": "https://replicate.com?ref={REF}",
    "env": "REPLICATE_REF"
  },
  "fal-ai": {
    "name": "Fal.ai",
    "url": "https://fal.ai",
    "template": "https://fal.ai",
    "env": null
  },
  "salad": {
    "name": "Salad",
    "url": "https://salad.com",
    "template": "https://salad.com/?ref={REF}",
    "env": "SALAD_REF"
  },
  "fluidstack": {
    "name": "FluidStack",
    "url": "https://www.fluidstack.io",
    "template": "https://www.fluidstack.io/?ref={REF}",
    "env": "FLUIDSTACK_REF"
  },
  "datacrunch": {
    "name": "DataCrunch",
    "url": "https://datacrunch.io",
    "template": "https://datacrunch.io?ref={REF}",
    "env": "DATACRUNCH_REF"
  }
};
