/**
 * Emits the provider redirect map consumed by functions/go/[partner].ts.
 *
 * Pages Functions are deployed by copying functions/ into dist/, so they
 * cannot import from data/ at runtime. Generating the map keeps
 * providers.json the single source of truth; audit-affiliates.ts fails the
 * build if the committed output has drifted.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

interface Provider {
  slug: string;
  name: string;
  url: string;
  affiliate_url_template: string;
  affiliate_param_env: string | null;
}

const providers = JSON.parse(
  readFileSync(path.resolve('data/providers.json'), 'utf-8')
) as Provider[];

const map = Object.fromEntries(
  providers.map((p) => [
    p.slug,
    { name: p.name, url: p.url, template: p.affiliate_url_template || null, env: p.affiliate_param_env },
  ])
);

const out = `// Generated by scripts/generate-functions-data.ts — do not edit.
// Source: data/providers.json

export interface ProviderRedirect {
  name: string;
  url: string;
  template: string | null;
  env: string | null;
}

export const PROVIDERS: Record<string, ProviderRedirect> = ${JSON.stringify(map, null, 2)};
`;

mkdirSync(path.resolve('functions/_generated'), { recursive: true });
writeFileSync(path.resolve('functions/_generated/providers.ts'), out);
console.log(`Wrote functions/_generated/providers.ts (${providers.length} providers)`);
